server:
  port: 8005
spring:
  thymeleaf:
    cache: false
  application:
    name: pwol-search-consumer
eureka:
  instance:
    instance-id: pwol-search-consumer   #自定义服务名称信息
    prefer-ip-address: true     #访问路径可以显示IP地址
  client:
    service-url:
      defaultZone: http://localhost:6001/eureka/
feign:
  hystrix:
    enabled: true
cloud-producer:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

