server:
  port: 8003
eureka:
  client:
    service-url:
#      defaultZone: http://47.93.30.178:6001/eureka/
       defaultZone: http://localhost:8080/eureka/
spring:
  application:
    name: pwonline-orders-provider
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
  datasource:
    url: jdbc:mysql://localhost:3306/orders
    username: ppp
    password: ppp
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    name: orders
  profiles:
    active: dev
  rabbitmq:
      host: 127.0.0.1
      port: 5672
      username: liuzeminm
      password: liuzeminm
      virtual-host: /
      publisher-confirms: true
      publisher-returns: true
logging:
  level: debug
---
mybatis:
  mapperLocations: classpath:mapper/*.xml
management:
  endpoints:
    web:
      exposure:
        include: "*"
#  zipkin:
#    base-url: http://localhost:7700
#  sleuth:
#    sampler:
#      percentage: 1.0
