server:
  port: 8004
spring:
  application:
    name: pwonline-orders-consumer
#  zipkin:

#    base-url: http://localhost:7700
#  sleuth:
#    sampler:
#      percentage: 1.0
  mvc:
    view:
      prefix: /templates/
      suffix: .html
    static-path-pattern: /static/**
  rabbitmq:
      host: 127.0.0.1
      port: 5672
      username: liuzeminm
      password: liuzeminm
      virtual-host: /
      publisher-confirms: true
      publisher-returns: true
      #非公平分发 能者多劳
      listener:
        simple:
          prefetch: 1
eureka:
  client:
    service-url:
#      defaultZone: http://47.93.30.178:6001/eureka/
      defaultZone: http://localhost:8080/eureka/
feign:
  hystrix:
    enabled: true

demo-usr-provider:
  ribbon:
    NFloadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
logging:
  level: debug
